[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Lordfirespeed"
name = "OdinSerializer"
description = "Fast, robust, powerful and extendible .NET serializer built for Unity"
websiteUrl = "https://github.com/lordfirespeed/odinserializerthunderstore"
containsNsfwContent = false
[package.dependencies]

[build]
icon = "./icons/odin-serializer.png"
readme = "../obj/README.md"
outdir = "../dist"

[[build.copy]]
source = "../../Build/Assets/Plugins/Sirenix/Odin Serializer/JIT/netstandard2.1/OdinSerializer.dll"
target = "/BepInEx/core/OdinSerializer/OdinSerializer.dll"

[[build.copy]]
source = "../../Build/Assets/Plugins/Sirenix/Odin Serializer/JIT/netstandard2.1/OdinSerializer.pdb"
target = "/BepInEx/core/OdinSerializer/OdinSerializer.pdb"

[[build.copy]]
source = "../../submodules/odin-serializer/LICENSE"
target = "/"


[publish]
communities = [ "lethal-company", "repo" ]
[publish.categories]
lethal-company = [ "tools", "libraries", "misc", ]
repo = [ "tools", "libraries", "misc", ]
