name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [ main ]

  # Trigger the workflow on any pull request
  pull_request:

  # Trigger the workflow when called by another workflow
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || null }}
          fetch-depth: 0
          filter: tree:0
          submodules: recursive

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Restore Solution Tools
        run: dotnet tool restore

      - name: Restore BuildThunderstore
        run: dotnet restore BuildThunderstore

      - name: Generate Sources
        run: |
          dotnet build BuildThunderstore -target:GeneratePatchedSource

      - name: Restore OdinSerializer
        run: dotnet restore OdinSerializer

      - name: Build OdinSerializer
        run: |
          dotnet build OdinSerializer -c "Release JIT"

      - name: Pack Thunderstore
        run: |
          dotnet build BuildThunderstore -c "Release JIT" -target:PackThunderstore

      - name: Upload thunderstore artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: BuildThunderstore/dist/*.zip
